name: spring-skb-lab

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-todo}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: